site_name: Spelman Innovaiton Lab Docs

site_url: https://spelmanil.github.io/docs

site_dir: '../docs'

theme:
  name: 'readthedocs'
  custom_dir: 'custom_theme'

nav:
    - Home: index.md
    - Unity & GitHub: Unity_and_GitHub.md
    - Page1: page1.md
