site_name: Spelman Innovaiton Lab Docs

site_url: https://spelmanil.github.io/docs

site_dir: '../docs'

theme:
  name: 'readthedocs'
  custom_dir: 'custom_theme'

markdown_extensions:
  - admonition

nav:
    - Home: index.md
    - IL Programs: il_programs/il_programs.md
    - SpelmanVR: unity/unity.md
#    - Template: template.md
